### ISSUE TITLE
Does not compile in Visual Studio 17.14.11

### ISSUE THREAD

**Issue by cedricleca** [hlavacs/GameJobSystem#4]
The compilation fails with the following errors : 

`1>H:\Dev\GameTemplate\vienna\include\VGJS.h(57,92): warning C4003: not enough arguments for function-like macro invocation 'max'
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(57,92): error C2589: '(': illegal token on right side of '::'
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(57,92): error C2059: syntax error: ')'
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(57,92): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(393,35): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(393,35): error C3203: 'VgjsQueue': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(394,35): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(394,35): error C3203: 'VgjsQueue': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(396,35): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(396,35): error C3203: 'VgjsQueue': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(397,35): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(397,35): error C3203: 'VgjsQueue': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(400,65): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(400,65): error C3203: 'VgjsQueue': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
1>(compiling source file 'Engine/Settings.ixx')
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(637,13): error C2976: 'vgjs::VgjsQueue': too few template arguments
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(637,39): error C2955: 'vgjs::VgjsQueue': use of class template requires template argument list
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(306,11):
1>    see declaration of 'vgjs::VgjsQueue'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(642,45): error C2440: '=': cannot convert from 'int *' to 'vgjs::VgjsQueue *'
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(642,45):
1>    Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(644,48): error C2662: 'auto vgjs::VgjsQueue<T,SYNC,LIMIT>::size(void) noexcept': cannot convert 'this' pointer from 'vgjs::VgjsQueue' to 'vgjs::VgjsQueue<T,SYNC,LIMIT> &'
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(644,41):
1>    Reason: cannot convert from 'vgjs::VgjsQueue' to 'vgjs::VgjsQueue<T,SYNC,LIMIT>'
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(644,41):
1>    Conversion requires a second user-defined-conversion operator or constructor
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(329,14):
1>    see declaration of 'vgjs::VgjsQueue<T,SYNC,LIMIT>::size'
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(644,48):
1>    while trying to match the argument list '()'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(651,51): error C2662: 'T *vgjs::VgjsQueue<T,SYNC,LIMIT>::pop(void) noexcept': cannot convert 'this' pointer from 'vgjs::VgjsQueue' to 'vgjs::VgjsQueue<T,SYNC,LIMIT> &'
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(651,44):
1>    Reason: cannot convert from 'vgjs::VgjsQueue' to 'vgjs::VgjsQueue<T,SYNC,LIMIT>'
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(651,44):
1>    Conversion requires a second user-defined-conversion operator or constructor
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(359,12):
1>    see declaration of 'vgjs::VgjsQueue<T,SYNC,LIMIT>::pop'
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(651,51):
1>    while trying to match the argument list '()'
1>H:\Dev\GameTemplate\vienna\include\VGJS.h(651,42): error C2440: 'initializing': cannot convert from 'T *' to 'vgjs::VgjsJobParentPointer'
1>(compiling source file 'Engine/Settings.ixx')
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(651,42):
1>    Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>H:\Dev\GameTemplate\Engine\Settings.ixx(156,9): error C2039: 'schedule': is not a member of 'vgjs'
1>    H:\Dev\GameTemplate\vienna\include\VGJS.h(29,11):
1>    see declaration of 'vgjs'
1>H:\Dev\GameTemplate\Engine\Settings.ixx(156,9): error C3861: 'schedule': identifier not found`

**Comment by cedricleca** [comment]
Update on that issue :
Including vgjs.h before windows.h solved it.
Sorry about that.
